### ISSUE TITLE
Installation scripts fails to install qtserialport

### ISSUE THREAD

**Issue by lazim2142** [mllofriu/robobulls2#2]
Qt 5.2.1 does not seem to have qtserialport by default, so it should be installed manually by the install script. Higher Qt versions may have qtserialport, but they require an interactive install as opposed to automatic terminal installation using apt-get.

**Comment by mllofriu** [comment]
Isn't this package doing it libqt5serialport5-dev? Isn't Qt 4 the one with problems?

From the script:
sudo apt-get install -y git g++ make libprotobuf-dev protobuf-compiler libgtkmm-2.4-dev qt5-default qtbase5-private-dev qt5-qmake qtcreator **libqt5serialport5-dev** libsdl2-dev minicom build-essential cmake libqt4-dev libgl1-mesa-dev libglu1-mesa-dev libode-dev

**Comment by lazim2142** [comment]
No I was running qt 5.2.1 the whole time. Never tried to fix for qt4

On Dec 13, 2016 10:23 AM, Martin Llofriu <notifications@github.com> wrote:

Isn't this package doing it libqt5serialport5-dev? Isn't Qt 4 the one with problems?

From the script:
sudo apt-get install -y git g++ make libprotobuf-dev protobuf-compiler libgtkmm-2.4-dev qt5-default qtbase5-private-dev qt5-qmake qtcreator libqt5serialport5-dev libsdl2-dev minicom build-essential cmake libqt4-dev libgl1-mesa-dev libglu1-mesa-dev libode-dev

**Comment by mllofriu** [comment]
The serial works for me (Ubuntu 16.04, Qt  5.5.1, libqt5serialport5-dev installed). No custom install.
